CREATE TABLE IF NOT EXISTS Library (
	id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name TEXT,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Library_Audit (
	auditID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	id BIGINT,
	name TEXT,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


DELIMITER //

CREATE TRIGGER lib_audit_before_update
BEFORE UPDATE ON Library
FOR EACH ROW
BEGIN
    INSERT INTO Library_Audit (id, name) VALUES (OLD.id, OLD.name);
END; //

DELIMITER ;


DELIMITER //

CREATE TRIGGER lib_audit_before_delete
BEFORE DELETE ON Library
FOR EACH ROW
BEGIN
    INSERT INTO Library_Audit (id, name) VALUES (OLD.id, OLD.name);
END; //

DELIMITER ;
